@startuml

left to right direction

class "契約" {
    - プラン
    + 支払料金を確認する()
}

class "プラン" {
    - プラン名
    - 容量
    - List<オプション>
    + オプション購入可能かどうか判断する()
}

class "容量" {
    - 容量名
    - 月額料金
}

class "オプション" {
    - オプション名
    - 購入条件
    - 月額料金
    + 購入可能か()
}

note top of オプション
どの容量プランであれば、
購入できるか
end note

契約 --> プラン
プラン --> 容量
プラン "1" --> "*" オプション
オプション --> 容量

@enduml